typography_spectrum: 0.7760472
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.9045047266408801
  lightness: 0.2873762638773769
  saturation: 0.5078556111548096
  rhythmicContrast: 0.4886779678054154
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2894737
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Kyle Jackson
  email: k.jackson@talespin.company
  url: www.talespin.company
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/07d86750-677c-4e24-89b6-83b1fc3db04d.png'
name: Talespin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Evolution of content.
purpose:
  - name: follow
    url: null
    item: 2c44a4e4-d8eb-400b-ba58-fb24d41c4aa5
