name: Talespin
favicon: null
layout_spectrum: 0.88367
typography_spectrum: 0.24679
title: VR - The makings of a new language...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f1dd'
    - '#232426'
    - '#929a90'
    - '#3c413b'
    - '#aa7c66'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 2c44a4e4-d8eb-400b-ba58-fb24d41c4aa5
    url: null
