name: Talespin
favicon: null
layout_spectrum: 0.5225564
typography_spectrum: 0.39482
title: VR - The makings of a new language...
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#4A70B5'
    - '#E0EAF1'
    - '#2F4C88'
    - '#283042'
  brandStrength: 0.8888292
  lightness: 0.3410312
  saturation: 0.2701396
  rhythmicContrast: 1
purpose:
  - name: follow
    url: null
    item: 2c44a4e4-d8eb-400b-ba58-fb24d41c4aa5
