typography_spectrum: 0.7760472
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.45424062106758356
  lightness: 0.9429970474448055
  saturation: 0.2917133190203458
  rhythmicContrast: 0.6513745721895248
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2894737
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Kyle Jackson
  email: k.jackson@talespin.company
  url: www.talespin.company
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/07d86750-677c-4e24-89b6-83b1fc3db04d.png
name: Talespin
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Magic Leap
    id: b102d16a-1bed-4529-b8c6-2af214571afe
    type: content
  - name: AI
    id: 856ce623-ec3c-452f-9cf0-bb4e7015d146
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Evolution of content.
purpose: []
