name: Talespin
favicon: null
layout_spectrum: 0.51527
typography_spectrum: 0.49491
title: The makings of a new language
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f1dd'
    - '#232426'
    - '#929a90'
    - '#3c413b'
    - '#aa7c66'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: c68e3eaf-873c-444e-945c-e771a0b8b20b
    url: null
